#!/usr/bin/env python3
"""Build a committed regression fixture from a real bench run folder.

WHY A BUILDER AND NOT A HAND-WRITTEN FIXTURE
--------------------------------------------
The standing rule from the carhub contract tests applies here too: RE-CAPTURE
a fixture from hardware when the shape changes, NEVER hand-edit one to make a
test pass. A hand-written fixture in the test author's own vocabulary is what
let the dashboard blank silently. So the fixtures under tests/fixtures/ are
generated by this script from `analysis/bench-*/`, which is gitignored -- the
inputs stay local, the distilled fixture is committed.

WHAT IT KEEPS, AND WHY IT IS MINIMAL
------------------------------------
Only what the verdict logic reads:
  * the FIRST and LAST sample (claim 5 baseline, the summary numbers)
  * every sample where deleted_acked or deleted_unacked changes, plus the one
    before it, since the verdicts key on those transitions
  * a few low-usage samples carrying unrecorded loss (claim 4)
  * every eviction, as RAW facts -- index, tier, watermark, and the files on
    disk at that moment -- so the test drives the real scoping rule in
    Watcher.record_eviction() rather than asserting a precomputed number.

USAGE
    python tools/make_verdict_fixture.py \\
        --run analysis/bench-2026-09-24-1901 \\
        --name claim2_pass_1901 \\
        --baseline-lost 34
"""

from __future__ import annotations

import argparse
import csv
import json
import re
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
FIXTURES = REPO / "tests" / "fixtures"

EVICT_RE = re.compile(
    r"\[t=\s*(?P<t>[\d.]+)\]\s*EVICTED\s*#(?P<index>\d+)\s*"
    r"tier=(?P<tier>\w+)\s*kind=(?P<kind>\w+)\s*bytes=(?P<bytes>\d+)\s*"
    r"acked=(?P<acked>\w+)")
CLOSED_RE = re.compile(
    r"closed\s*#(?P<index>\d+)\s*tier\s*(?P<tier>\w)\s*kind\s*(?P<kind>\w+)")

NUMERIC = {"t", "uptime_ms", "used", "total", "usage_pct", "warn_pct", "files",
           "open", "acked_through", "tier_a", "tier_b", "tier_c",
           "pending_unacked", "deleted_acked", "deleted_unacked",
           "lost_a", "lost_b", "lost_c", "lost_bytes_a", "lost_bytes_b",
           "lost_bytes_c", "lost_files_total", "loss_recorded_files",
           "write_errors", "rows_dropped"}


def read_text(path: Path) -> str:
    """Logs are written by PowerShell Tee-Object, so they may be UTF-16."""
    raw = path.read_bytes()
    for enc in ("utf-8", "utf-16", "utf-16-le"):
        try:
            text = raw.decode(enc)
        except (UnicodeDecodeError, UnicodeError):
            continue
        if text.count("\x00") == 0:
            return text
    return raw.decode("utf-8", errors="replace")


def typed(row: dict) -> dict:
    out: dict = {}
    for k, v in row.items():
        if k is None:
            continue
        if v in ("", None):
            out[k] = None
        elif k == "warn" or k == "tier_counters_present":
            out[k] = str(v).strip().lower() == "true"
        elif k in NUMERIC:
            out[k] = float(v) if k == "t" else int(float(v))
        else:
            out[k] = v
    return out


def pick_rows(rows: list[dict]) -> list[dict]:
    """The smallest subset the verdicts still read identically."""
    if not rows:
        return []
    keep: set[int] = {0, len(rows) - 1}
    prev = rows[0]
    for n, r in enumerate(rows[1:], start=1):
        if (r.get("deleted_acked") or 0) != (prev.get("deleted_acked") or 0) or \
           (r.get("deleted_unacked") or 0) != (prev.get("deleted_unacked") or 0):
            keep.add(n - 1)
            keep.add(n)
        prev = r
    # Claim 4 scans for low usage carrying unrecorded loss; keep a few.
    low = [n for n, r in enumerate(rows)
           if (r.get("usage_pct") or 0) < (r.get("warn_pct") or 70)
           and (r.get("lost_files_total") or 0) > (r.get("loss_recorded_files") or 0)]
    keep.update(low[:3])
    return [rows[n] for n in sorted(keep)]


def build(run: Path, baseline_lost: int | None) -> dict:
    rows = [typed(r) for r in
            csv.DictReader(read_text(run / "retention.csv").splitlines())]
    log = read_text(run / "retention.log")

    tiers: dict[int, str] = {}
    serial = run / "serial.log"
    if serial.exists():
        for m in CLOSED_RE.finditer(read_text(serial)):
            tiers[int(m.group("index"))] = m.group("tier")

    # Replay the eviction sequence to reconstruct what was on disk each time.
    evictions: list[dict] = []
    order = [m.groupdict() for m in EVICT_RE.finditer(log)]
    all_seen = sorted(tiers)
    removed: set[int] = set()
    for e in order:
        idx = int(e["index"])
        t = float(e["t"])
        wm = None
        for r in rows:
            if r["t"] <= t:
                wm = r.get("acked_through")
        on_disk = [{"index": j, "tier": tiers.get(j, "?")}
                   for j in all_seen if j not in removed and j != idx]
        evictions.append({
            "t": t, "index": idx,
            "file": {"tier": e["tier"], "kind": e["kind"],
                     "bytes": int(e["bytes"]), "synthetic": True},
            "acked_through": wm,
            "on_disk": on_disk,
        })
        removed.add(idx)

    kept = pick_rows(rows)
    return {
        "source_run": run.name,
        "note": ("Generated by tools/make_verdict_fixture.py from a real bench "
                 "run. Do NOT hand-edit to make a test pass -- regenerate."),
        "baseline_lost": baseline_lost,
        "total_samples": len(rows),
        "rows": kept,
        "evictions": evictions,
    }


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--run", required=True)
    ap.add_argument("--name", required=True)
    ap.add_argument("--baseline-lost", type=int, default=None)
    args = ap.parse_args()

    run = Path(args.run)
    if not run.is_absolute():
        run = REPO / run
    if not (run / "retention.csv").exists():
        raise SystemExit(f"FATAL: {run}/retention.csv not found")

    fixture = build(run, args.baseline_lost)
    FIXTURES.mkdir(parents=True, exist_ok=True)
    out = FIXTURES / f"{args.name}.json"
    out.write_text(json.dumps(fixture, indent=2) + "\n", encoding="utf-8")
    print(f"wrote {out.relative_to(REPO)}  "
          f"({len(fixture['rows'])} of {fixture['total_samples']} samples, "
          f"{len(fixture['evictions'])} eviction(s))")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
